### PR TITLE
add nav bar feature

### PR DESCRIPTION
**Pull request by gitaukelvin**
hey guys please spare a minute or two to review my work.

[nav bar with the a search button, sign up and sign in links]

### CODE REVIEW

**Comment by gitaukelvin** [comment]
Navigation-bar Design
user should be able to view the sign-in and sign-up links
searchbar
sign-in 
sign-up links
desktop-view
mobile-view
mobile-view2

**Comment by Enockkenya** [comment]
Nice nav but you still have a lot to do in the next 24hrs remember there is a deadline for submission

**Comment by Gidraf** [comment]
I like it's responsive

**Comment by gitaukelvin** [comment]
Thanks guys..will definitely do that now and from now on

**Comment by gitaukelvin** [comment]
thanks..working on my sign-up page now

**Pull request merged**
